### PR TITLE
Fix build problem of tbro_apache

### LINKED ISSUE #2: Build of tbro_apache fails because of pear.propelorm.org not being found
Error message from build:

```
Step 4 : RUN pear channel-discover pear.propelorm.org
Discovering channel pear.propelorm.org over http:// failed with message: channel-add: Cannot open "http://pear.propelorm.org/channel.xml" (Connection to `pear.propelorm.org:80' failed: Connection refused)
Trying to discover channel pear.propelorm.org over https:// instead
Discovery of channel "pear.propelorm.org" failed (channel-add: Cannot open "https://pear.propelorm.org/channel.xml" (Connection to `pear.propelorm.org:443' failed: Connection refused)) 
```

For ubuntu 15.04 the apt repository `php-propel-runtime` is available - unfortunately not for ubuntu 14.04.

### PR DESCRIPTION
**Pull request by iimog**
Fix #2 by using composer instead of pear for propel installation

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/TBroTeam/Docker/pull/4" target="_blank">ReviewNinja

**Comment by greatfireball** [comment]
I am currently trying to generate a new image using manually triggered build of this branch at dockerhub

**Comment by greatfireball** [comment]
Docker-Hub build succeeded

https://hub.docker.com/r/tbroteam/tbro_apache/builds/bzefmsakajvarqqqh5pasmd/

**Comment by greatfireball** [comment]
line #102 include installation of Console_Table again!

**Comment by greatfireball** [comment]
Include `. ~/.bash_profile` into build_installation.sh script to add phing to path!

**Comment by greatfireball** [comment]
Seems that propel is still not working!

**Comment by greatfireball** [comment]
tbro_apache build works https://hub.docker.com/r/tbroteam/tbro_apache/builds/bjzvnr2jov2y4bp2azk6gcg/
tbro_demo container build works locally

**Pull request merged**
